spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/sims_ppob
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: prodemy

cloudinary:
  name: ${DEV_CLOUDINARY_NAME}
  api-key: ${DEV_CLOUDINARY_API_KEY}
  api-secret : ${DEV_CLOUDINARY_API_SECRET}
