spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true